language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - source setup_module.sh
  - source setup.sh

install:
  - pip3 install --upgrade pip
  - pip3 install -U sklearn keras sqlalchemy numpy kubernetes psycopg2-binary benedict flask-login future
  - pip3 install -U Gaugi

script:
  - python3 ci/main.py
